In [1]:
import numpy as np

### 1 - Create a new array of 2*2 integers, without initializing entries.

In [109]:
emptyArray = np.empty([2,2], int)
emptyArray

array([[0, 0],
       [0, 0]])

In [110]:
emptyArray.shape

(2, 2)

#### Return ndarray - Array of uninitialized (arbitrary) data of the given shape, dtype, and order. 

In [5]:
emptyArray

array([[446753168,       457],
       [        0,         0]])

### 2 - Let X = np.array([1,2,3], [4,5,6], np.int32). Create a new array with the same shape and type as X.

In [111]:
X = np.array([[1,2,3], [4,5,6]], np.int32)
X

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
X.shape

(2, 3)

In [112]:
XA = np.empty_like(X)

In [115]:
XA.shape

(2, 3)

### 3 - Create a 3-D array with ones on the diagonal and zeros elsewhere

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [116]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 4 - Create a new array of 3*2 float numbers, filled with ones.

In [117]:
np.ones([3,2],float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### 5 - Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [118]:
range(4)

range(0, 4)

In [18]:
X = np.arange(4, dtype=np.int64)
X

array([0, 1, 2, 3], dtype=int64)

In [19]:
np.ones_like(X)

array([1, 1, 1, 1], dtype=int64)

### 6 - Create a new array of 2*5 uints, filled with 6.

In [119]:
np.ones([2,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
6*np.ones([2,5])

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [25]:
np.full((2, 5), 6, dtype=np.int64)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=int64)

### 7 - Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [27]:
X = np.arange(4, dtype=np.int64)
X

array([0, 1, 2, 3], dtype=int64)

In [29]:
6 * np.ones_like(X)

array([6, 6, 6, 6], dtype=int64)

In [31]:
np.full_like(X, 6)

array([6, 6, 6, 6], dtype=int64)

### From existing data

### 8 - Create an array of [1, 2, 3].

In [35]:
X = np.array([1,2,3])
X

array([1, 2, 3])

In [36]:
print("Shape = {}".format(X.shape))

Shape = (3,)


In [48]:
X = np.array([[1,2,3]])
X

array([[1, 2, 3]])

In [49]:
print("Shape = {}".format(X.shape))

Shape = (1, 3)


In [ ]:
[1,2,3]
1X3 - [[1,2,3]]
3X1 - [[1],[2],[3]]

In [50]:
X = np.array([[1],[2],[3]])
X

array([[1],
       [2],
       [3]])

In [51]:
print("Shape = {}".format(X.shape))

Shape = (3, 1)


### 9 - Let x = [1, 2]. Convert it into an array.

In [37]:
x = [1,2]
X = np.array(x)
X

array([1, 2])

### 10 - Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [38]:
X = np.array([[1, 2], [3, 4]])
X

array([[1, 2],
       [3, 4]])

In [39]:
print("Shape = {}".format(X.shape))

Shape = (2, 2)


In [41]:
mat = np.asmatrix(X)
mat

matrix([[1, 2],
        [3, 4]])

### 11 - Let x = [1, 2]. Conver it into an array of float.

In [59]:
x = [1,2]
X = np.array([1,2],dtype=np.float64)
X

array([1., 2.])

### 13 - Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [63]:
X = np.array([30])
X

array([30])

In [65]:
X[0]

30

### 14 - Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [120]:
X = np.array([1, 2, 3])
X

array([1, 2, 3])

In [121]:
id(X)

1963585360112

In [122]:
XA = X

In [123]:
id(XA)

1963585360112

In [124]:
X1 = X.copy()
id(X1)

1963585363088

In [125]:
id(X) == id(X1)

False

### Numerical ranges
### 15 - Create an array of 2, 4, 6, 8, ..., 100.

In [132]:
t = []
for i in range(2,101,2) :
    t.append(i)
#print(t)
X = np.array(t)
X.reshape(10,5)

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [72]:
np.arange(2, 101, 2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### 16 - Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [75]:
X = np.linspace(3, 10, 50)
X

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

In [77]:
X.shape

(50,)

In [81]:
X1 = X.reshape([5,10])
X1

array([[ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
         3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429],
       [ 4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
         5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571],
       [ 5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
         6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714],
       [ 7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
         8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857],
       [ 8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
         9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ]])

In [82]:
X1.shape

(5, 10)

### Building matrices
### 17. Let X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]]). Get the diagonal of X, that is, [0, 5, 10].

In [108]:
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [84]:
X.shape

(3, 4)

In [85]:
X.diagonal()

array([ 0,  5, 10])

### 18. Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [86]:
np.diagflat([1, 2, 3, 4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### 19. Create an array which looks like below. array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])

In [93]:
X = np.array([[ 0., 0., 0., 0., 0.], [ 1., 0., 0., 0., 0.], [ 1., 1., 0., 0., 0.]])
X

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [102]:
np.tri(3, 5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

### 20. Create an array which looks like below. array([[ 0, 0, 0], [ 4, 0, 0], [ 7, 8, 0], [10, 11, 12]])

In [104]:
X = np.array([[ 0, 0, 0], [ 4, 0, 0], [ 7, 8, 0], [10, 11, 12]])
X

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [105]:
np.tril(np.arange(1, 13).reshape(4, 3), -1)

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

### 21. Create an array which looks like below. array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])

In [106]:
X = np.array([[ 1, 2, 3], [ 4, 5, 6], [ 0, 8, 9], [ 0, 0, 12]])
X

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [107]:
np.triu(np.arange(1, 13).reshape(4, 3), -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])