In [1]:
import numpy as np

### Array manipulation routines
### 1 - Let x be a ndarray [10, 10, 3] with all elements set to one. Reshape x so that the size of the second dimension equals 150.

In [9]:
X = np.ones([10,10,3])
print("Shape = {}".format(X.shape))

Shape = (10, 10, 3)


In [14]:
Xa = X.reshape(2,150)

In [19]:
print("Shape = {}".format(Xa.shape))

Shape = (2, 150)


In [20]:
X = np.ones([10, 10, 3])
out = np.reshape(X, [-1, 150])
print("Shape = {}".format(out.shape))

Shape = (2, 150)


### 2 - Let x be array [[1, 2, 3], [4, 5, 6]]. Convert it to [1 4 2 5 3 6].

In [22]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
print("Shape = {}".format(X.shape))

Shape = (2, 3)


In [30]:
X.tolist()

[[1, 2, 3], [4, 5, 6]]

In [32]:
Xt = X.transpose()
Xt_list = Xt.tolist()
Xt_list

[[1, 4], [2, 5], [3, 6]]

In [33]:
out1 = np.ravel(X, order='F')
out1

array([1, 4, 2, 5, 3, 6])

In [34]:
out2 = X.flatten(order="F")
out2

array([1, 4, 2, 5, 3, 6])

### 3 - Let x be array [[1, 2, 3], [4, 5, 6]]. Get the 5th element

In [35]:
X = np.array([[1, 2, 3], [4, 5, 6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
out = X.flatten(order="F")
out

array([1, 4, 2, 5, 3, 6])

In [38]:
out[4]

3

### 4. Let x be an arbitrary 3-D array of shape (3, 4, 5). Permute the dimensions of x such that the new shape will be (4,3,5).

In [39]:
X = np.zeros((3, 4, 5))
X.shape

(3, 4, 5)

In [46]:
test = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print("Shape = ",test.shape)
test

Shape =  (2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [45]:
np.swapaxes(test,0,2)

array([[[0, 4],
        [2, 6]],

       [[1, 5],
        [3, 7]]])

In [48]:
out1 = np.swapaxes(X, 1, 0)
out1.shape

(4, 3, 5)

### 5 - Let x be an arbitrary 2-D array of shape (3, 4). Permute the dimensions of x such that the new shape will be (4,3).

In [49]:
X = np.ones([3,4])
X

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [51]:
XA = np.swapaxes(X,0,1)
XA.shape

(4, 3)

In [52]:
XB = X.transpose()
XB.shape

(4, 3)

In [53]:
XC = X.T
XC.shape

(4, 3)

In [57]:
assert XA.shape == XB.shape == XC.shape

### 6. Let x be an arbitrary 2-D array of shape (3, 4). Insert a nex axis such that the new shape will be (3, 1, 4).

In [58]:
X = np.zeros((3, 4))
X.shape

(3, 4)

In [59]:
XA = np.expand_dims(X, axis=1)
XA.shape

(3, 1, 4)

### 7 - Let x be an arbitrary 3-D array of shape (3, 4, 1). Remove a single-dimensional entries such that the new shape will be (3, 4).

In [60]:
X = np.ones((3, 4, 1))
X.shape

(3, 4, 1)

In [61]:
XA = np.squeeze(X)
XA.shape

(3, 4)

### 8 - Lex x be an array [[ 1 2 3] [ 4 5 6]. and y be an array [[ 7 8 9] [10 11 12]].
### Concatenate x and y so that a new array looks like [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]].

In [64]:
X = np.array([[ 1, 2, 3],[ 4 ,5, 6]])
X.shape

(2, 3)

In [65]:
X

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
Y = np.array([[ 7, 8, 9], [10, 11, 12]])
Y.shape

(2, 3)

In [67]:
Y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [68]:
np.concatenate([X,Y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
np.concatenate([X,Y],1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [71]:
np.hstack((X, Y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [78]:
a = np.array((1,2,3))
b = np.array((4,5,6))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [79]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
a.shape

(3, 1)

(3,)

### 9 - Let x be an array [1 2 3] and y be [4 5 6]. Convert it to [[1, 4], [2, 5], [3, 6]].

In [81]:
X = np.array([1,2,3])
X.shape

(3,)

In [82]:
Y = np.array([4,5,6])
Y.shape

(3,)

In [87]:
np.hstack((X,Y))

array([1, 2, 3, 4, 5, 6])

In [94]:
np.column_stack((X,Y))

array([[1, 4],
       [2, 5],
       [3, 6]])